# Generated by Django 5.2.8 on 2025-11-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('press', 'Press')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/images/')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube o Vimeo', null=True)),
                ('press_link', models.URLField(blank=True, help_text='Enlace al artículo o entrevista', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
