# Generated by Django 5.2.8 on 2025-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='press_link',
            field=models.URLField(blank=True, help_text='Link to press article', null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL', null=True),
        ),
    ]
