# Generated by Django 5.2.8 on 2025-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('professional', 'Professional')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('years', models.CharField(help_text='Ejemplo: 2012–2015', max_length=50)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/')),
            ],
            options={
                'ordering': ['-years'],
            },
        ),
    ]
