# Generated by Django 5.2.8 on 2025-11-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.CharField(help_text='Example: 2012–2015', max_length=50),
        ),
    ]
